# Release docker compose configuration

version: "3.7"
services: 
    node:
        image: integrer/crypto-election-node:0.3.0-exonum-1.0.0
        links: [ exonum_launcher ]
#        ports: [ "8000:8000" ]
    exonum_launcher:
        image: integrer/exonum-launcher:0.3.0-exonum-launcher-0.2.0
    web:
        image: integrer/crypto-election-web:0.3.0-exonum-client-1.8.3
        links: [ node ]
        ports: [ "8008:8008" ]
