[package]
name = "crypto-election-core"
version = "0.1.0"
authors = ["Nikita Bibik <osbib2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#chrono = "0.4.9"
exonum = "0.12.0"
exonum-derive = "0.12.0"
exonum-merkledb = "0.12.0"
#geo = "0.12.2"
failure = "0.1.6"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
protobuf = "2.8.1"

[build-dependencies]
exonum-build = "0.12.0"
