[package]
name = "crypto-election-node"
version = "0.1.0"
authors = ["Nikita Bibik <osbib2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-election-core = {version = "0.1.0", path = "../core"}
exonum = "0.12.0"
exonum-derive = "0.12.0"
exonum-merkledb = "0.12.0"
exonum-crypto = "0.12.0"
exonum-configuration = "0.12.0"
serde = "1.0.101"
serde_derive = "1.0.101"
failure = "0.1.6"
protobuf = "2.8.1"

[dev-dependencies]
exonum-testkit = "0.12.0"
serde_json = "1.0.41"
pretty_assertions = "0.6.1"
assert_matches = "1.3.0" # orig - 1.2.0
hex = "0.4.0" # orig - 0.3.2

[build-dependencies]
exonum-build = "0.12.0"
