[package]
name = "crypto-election-web"
version = "0.1.0"
authors = ["Nikita Bibik <osbib2@gmail.com>"]
edition = "2018"

[[bin]]
name = "app"
path = "src/frontend/main.rs"

[dependencies]
crypto-election-core = {version = "0.1.0", path = "../core"}